---
title: 'Humana First Round Report'
author: "Edison Gu"
date: "03/01/2020"
output: html_document
---

```{r setup, include = F}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, cache = TRUE)

## Load libraries
library(tidyverse)
library(tibble)
library(janitor)
library(lubridate)
library(GGally)
library(ggpubr)
library(broom)
library(tree)
library(C50)
#library(alr4)
```

```{r Read in data}
## Read in data
library(readxl)
demo_df <- read_excel("Humana Case 2020 Q1 -- Data.xlsx", 
     sheet = "Demographics", col_types = c("text", 
         "numeric", "numeric", "numeric", 
         "numeric", "text", "text", "text", 
         "numeric", "numeric", "text", "text"))

claims_df <- read_excel("Humana Case 2020 Q1 -- Data.xlsx", 
    sheet = "Claims")

er_df <- read_excel("Humana Case 2020 Q1 -- Data.xlsx", 
    sheet = "ER Utilization")

pcp_df <- read_excel("Humana Case 2020 Q1 -- Data.xlsx", 
    sheet = "PCP Visits")

hospital_df <- read_excel("Humana Case 2020 Q1 -- Data.xlsx", 
    sheet = "Hospital Admissions")

rx_df <- read_excel("Humana Case 2020 Q1 -- Data.xlsx", 
    sheet = "Rx Utilization")
```


## Data Preparation

```{r Data Integration}
## Format data
claims = claims_df %>% 
        pivot_longer(-id, names_to = "time", values_to = "agg_claim") %>% 
        transmute(id = as.character(id),
               time = excel_numeric_to_date(as.numeric(time), 
                                            date_system = "modern" ),
               agg_claim)
        
er = er_df %>% 
        pivot_longer(-id, names_to = "time", values_to = "count") %>% 
        transmute(id = as.character(id),
               time = excel_numeric_to_date(as.numeric(time), 
                                            date_system = "modern" ),
               er_count = count)

pcp = pcp_df %>% 
        pivot_longer(-id, names_to = "time", values_to = "count") %>% 
        transmute(id = as.character(id),
               time = excel_numeric_to_date(as.numeric(time), 
                                            date_system = "modern" ),
               pcp_count = count)

hospital = hospital_df %>% 
        pivot_longer(-id, names_to = "time", values_to = "count") %>% 
        transmute(id = as.character(id),
               time = excel_numeric_to_date(as.numeric(time), 
                                            date_system = "modern" ),
               hospital_count = count)

rx = rx_df %>% 
        pivot_longer(-id, names_to = "time", values_to = "count") %>% 
        transmute(id = as.character(id),
               time = excel_numeric_to_date(as.numeric(time), 
                                            date_system = "modern" ),
               rx_count = count)
```

```{r Data Cleaning}
## Check counts
er %>% group_by(er_count) %>% 
    count() %>% arrange()
pcp %>% group_by(pcp_count) %>% 
    count() %>% arrange()
hospital %>% group_by(hospital_count) %>% 
    count() %>% arrange()
rx %>% group_by(rx_count) %>% 
    count() %>% arrange()
claims %>% group_by(agg_claim) %>% 
    count() %>% arrange() # assume mistyped a minus sign in front


## Check: each individual either get one or none CRD
demo_df %>% mutate(test_sum = transport+fin_assis+lonely+food_insec) %>% 
        filter(test_sum > 1)

## Check: region
demo_df %>% group_by(region) %>% 
    count() %>% arrange(n) # unknown small, ignore

## Check: rural
demo_df %>% group_by(rural) %>% 
    count() %>% arrange(n) # unknown small, ignore

## Check: is_lowincome
demo_df %>% group_by(is_lowincome) %>% 
    count() %>% arrange(n) # inconsistant label, need to fix

## Check: age
demo_df %>% group_by(age) %>% count() %>% filter(age<5) %>% arrange(age) # need to correct negative values, assume mistyped minues sign
demo_df %>% group_by(age) %>% count() %>% filter(age>95) %>% arrange(age) # need to correct >100 values, assume mistyped a 1 in the front

## Check: chronic_count
demo_df %>% group_by(chronic_count) %>% count() %>% arrange(chronic_count) # assume mistyped a 1 in the front

## Check: gender
demo_df %>% group_by(gender) %>% count() %>% arrange(n) # will just ignore other than M, F
    
demo = demo_df %>% 
    mutate(is_lowincome = demo_df$is_lowincome %in% c("Y","Yes","YES"),
           age = ifelse(age>110, age-100, abs(age)),
           mth_out = decimal_date(mdy(paste(mth_out,"1","2017"))),
           chronic_count = ifelse(chronic_count>=10,
                                  chronic_count-10,
                                  chronic_count)) %>% 
    filter(region != "Unknown" & rural != "Unknown" & gender %in% c("M","F"))

## Add a column indicate which CRD an individual received
crd = NA
for(i in 1:length(demo$id)){
        crd[i]=0
        if(demo$transport[i] == 1){
                crd[i] = 1
        }
        if(demo$fin_assis[i] == 1){
                crd[i] = 2
        }
         if(demo$lonely[i] == 1){
                crd[i] = 3
         }
         if(demo$food_insec[i] == 1){
                crd[i] = 4
         }
}
demo = demo %>% cbind(crd)

## Check: all NAs represent people from the control group
demo %>% filter(is.na(mth_out),
                crd !=0)
```

```{r Data Integration & Reduction 2}
## Join utilization and claim tables
loss = er %>% 
    inner_join(hospital, by = c("id"="id","time"="time")) %>% 
    inner_join(pcp, by = c("id"="id","time"="time")) %>% 
    inner_join(rx, by = c("id"="id","time"="time")) %>% 
    mutate(total_count = er_count+hospital_count+pcp_count+rx_count) %>% 
    inner_join(claims, by = c("id"="id","time"="time")) %>% 
    mutate(agg_claim = abs(agg_claim),
           avg_claim = ifelse(agg_claim*total_count!=0,agg_claim/total_count,0))

## Convert date to decimal year
loss = loss %>% mutate(time = decimal_date(time))

## Reduction
demo = demo %>% 
    select(id,region,rural,is_lowincome,age,chronic_count,gender,mth_out,crd)
remove(claims,claims_df,demo_df,er,er_df,hospital,hospital_df,pcp,pcp_df,rx,rx_df,crd,i)

## Join demo(features) with loss(responses)
impact = demo %>% inner_join(loss, by = "id")

## Add a column to indicate if row is after_crd
impact = impact %>% 
    mutate(after_crd = ifelse(!is.na(mth_out),time >= mth_out,NA))

#impact = impact %>% select(-mth_out)
```

## Exploratory Data Analysis

```{r Visualization EDA, eval = F}
## Pair-wise relationship in demo
demo %>% select(-id) %>% ggpairs()

## Average utilization (aka # of claims) across the entire population over time
loss %>% group_by(time) %>% 
    summarize(a=mean(er_count),b=mean(hospital_count),
              c=mean(pcp_count),d=mean(rx_count),e=mean(total_count))%>% 
    ggplot() +
    geom_line(aes(x=time,y=a),color="red",size=1.5)+
    geom_line(aes(x=time,y=b),color="blue",size=1.5)+
    geom_line(aes(x=time,y=c),color="green",size=1.5)+
    geom_line(aes(x=time,y=d),color="black",size=1.5)+
    geom_line(aes(x=time,y=e),color="magenta",size=1.5)+
    geom_smooth(aes(x=time,y=a),color="black",method="lm",size=0.5)+
    geom_smooth(aes(x=time,y=b),color="black",method="lm",size=0.5)+
    geom_smooth(aes(x=time,y=c),color="black",method="lm",size=0.5)+
    geom_smooth(aes(x=time,y=d),color="black",method="lm",size=0.5)+
    geom_smooth(aes(x=time,y=e),color="black",method="lm",size=0.5)

## Average utilization (aka # of claims) across the entire population over time
loss %>% group_by(time) %>% 
    summarize(avg_agg_claim=mean(agg_claim),avg_avg_claim=mean(avg_claim))%>% 
    ggplot() +
    geom_line(aes(x=time,y=avg_agg_claim),color="red",size=1.5)+
    geom_line(aes(x=time,y=avg_avg_claim),color="blue",size=1.5)+
    geom_smooth(aes(x=time,y=avg_agg_claim),color="black",method="lm",size=0.5)+
    geom_smooth(aes(x=time,y=avg_avg_claim),color="black",method="lm",size=0.5)
```

```{r Separate the data, eval = F}
out = sort(unique(impact$mth_out))
before=list()
after=list()
for(i in 1:length(out)){
        tmp = impact %>% filter(mth_out==out[i])
        before[[i]] = tmp %>% filter(after_crd==F)
        #write.csv(before[[i]],paste('before_received_crd_in_month_',i,'.csv'))
        after[[i]] = tmp %>% filter(after_crd==T)
        #write.csv(after[[i]],paste('after_received_crd_in_month_',i,'.csv'))
}
not_control = impact %>% filter(!is.na(mth_out))
control = impact %>% filter(is.na(mth_out))
#write.csv(control,paste('control.csv'))
```

## Misc.

```{r important discovery, eval=F}
tmp = control

log_claim = log(tmp$agg_claim)

#tmp %>% ggplot() + geom_density(aes(x=log_claim))
#tmp %>% ggplot() + geom_bar(aes(x=total_count))
tmp %>% ggplot() + geom_point(aes(x=time,y=log_claim,color=factor(er_count)),alpha=0.1)
tmp %>% ggplot() + geom_point(aes(x=time,y=log_claim,color=factor(hospital_count)),alpha=0.1)
tmp %>% ggplot() + geom_point(aes(x=time,y=log_claim,color=factor(rx_count)),alpha=0.3)
tmp %>% ggplot() + geom_point(aes(x=time,y=log_claim,color=factor(pcp_count)),alpha=0.3)

ggplot(data = tmp) +
    geom_point(mapping = aes(x = time, y = log_claim),alpha=0.1) + 
    facet_grid(rows = vars(er_count), cols = vars(hospital_count))
```

```{r, eval=F}
tmp = control

log_claim = log(tmp$agg_claim)

#tmp %>% ggplot() + geom_density(aes(x=log_claim))
#tmp %>% ggplot() + geom_bar(aes(x=total_count))


tmp %>% filter(er_count>0) %>% 
    ggplot() + geom_point(aes(x=time,y=log(agg_claim),color=factor(er_count)),alpha=0.3) + ylim(4,10)
tmp %>% filter(hospital_count>0) %>% 
    ggplot() + geom_point(aes(x=time,y=log(agg_claim),color=factor(hospital_count)),alpha=0.3)+ ylim(4,10)
tmp %>% filter(rx_count>0) %>% 
    ggplot() + geom_point(aes(x=time,y=log(agg_claim),color=factor(rx_count)),alpha=0.3)+ ylim(4,10)
tmp %>% filter(pcp_count>0) %>% 
    ggplot() + geom_point(aes(x=time,y=log(agg_claim),color=factor(pcp_count)),alpha=0.3)+ ylim(4,10)

ggplot(data = tmp) +
    geom_point(mapping = aes(x = time, y = log_claim),alpha=0.1) + 
    facet_grid(rows = vars(er_count), cols = vars(rx_count))
ggplot(data = tmp) +
    geom_point(mapping = aes(x = time, y = log_claim),alpha=0.1) + 
    facet_grid(rows = vars(rx_count), cols = vars(er_count))
```

```{r, eval=F}
tmp = control
er_claim=0
hospital_claim=0
pcp_claim=0
rx_claim=0
er_claim = ifelse((er_count>0)&(hospital_count*pcp_count*rx_count==0),
                                       agg_claim/er_count,
                                       avg_claim)
hospital_claim = ifelse((hospital_count>0)&(er_count*pcp_count*rx_count==0),
                                       agg_claim/hospital_count,
                                       avg_claim)
pcp_claim = ifelse((pcp_count>0)&(er_count*hospital_count*rx_count==0),
                                       agg_claim/pcp_count,
                                       avg_claim)
rx_claim = ifelse((rx_count>0)&(hospital_count*pcp_count*pcp_count==0),
                                       agg_claim/rx_count,
                                       avg_claim)
tmp = tmp %>% cbind(er_claim,hospital_claim,pcp_claim,rx_claim)
log_claim = log(tmp$agg_claim)
#sort(((tmp$er_claim)),decreasing =T)
tmp %>% ggplot() + geom_point(aes(x=time,y=log(er_claim),color=factor(er_count)),alpha=0.1)+ ylim(4,10)
tmp %>% ggplot() + geom_point(aes(x=time,y=log(hospital_claim),color=factor(hospital_count)),alpha=0.1)+ ylim(4,10)
tmp %>% ggplot() + geom_point(aes(x=time,y=log(rx_claim),color=factor(rx_count)),alpha=0.3)+ ylim(4,10)
tmp %>% ggplot() + geom_point(aes(x=time,y=log(pcp_claim),color=factor(pcp_count)),alpha=0.3)+ ylim(4,10)
```

```{r, eval=F}
attach(control)
tmp = control
model1 = lm(log(agg_claim+1)~er_count*hospital_count*rx_count*pcp_count+
                time+gender+age*factor(chronic_count))
summary(model1)
tmp = tmp %>% cbind(fit = fitted(model1),res = residuals(model1))

ggplot(data=tmp) + geom_point(mapping=aes(x=fit,y=res,color=region),alpha=0.5)

ggplot(data=tmp) + geom_boxplot(mapping=aes(x=factor(chronic_count),y=res))
ggplot(data=tmp) + geom_boxplot(mapping=aes(x=factor(age),y=res))

ggplot(data=tmp,mapping=aes(x=age,y=res)) + geom_point(alpha=0.1)
ggplot(data=tmp,mapping=aes(x=factor(chronic_count),y=res)) + geom_jitter(alpha=0.1)


ggplot(data = tmp) +
    geom_point(mapping = aes(x = fit, y = res),alpha=0.1) + 
    facet_grid(rows = vars(cut(age,c(0,20,40,60,80,100,120))), cols = vars(factor(chronic_count)))


ggplot(data=tmp) + geom_jitter(mapping=aes(x=age,y=factor(chronic_count)),alpha=0.1)

ggplot(data=tmp) + geom_density(aes(x=age))
ggplot(data=tmp) + geom_bar(aes(x=factor(chronic_count)))
```

```{r Build model for before and after outreach, eval=F}
attach(impact)
tmp = impact
sin_term = sin(2*pi*impact$time)
cos_term = cos(2*pi*impact$time)
time_sq <- impact$time^2 # will use later
time_cu <- impact$time^3 # will use later

## Frequency model
model_total_count = glm(total_count ~ sin_term + cos_term + time + 
                           region + rural + is_lowincome + age + 
                           chronic_count + factor(crd),
                        family = poisson)
model1 = model_total_count
summary(model1)
tmp = tmp %>% cbind(fit = fitted(model1),res = residuals(model1))
#ggplot(data=tmp) + geom_point(mapping=aes(x=fit,y=res,color=factor(crd)))
#ggplot(data=tmp) + geom_point(mapping=aes(x=fit,y=res,color=factor(region)))

```

```{r calculate monthly avg for before and after, eval=F}
impact %>% 
    group_by(after_crd,time) %>% 
    summarize(monthly_total_count = mean(total_count),
              monthly_agg_claim = mean(agg_claim),
              monthly_avg_claim = mean(avg_claim)) %>%
    ggplot(aes(x=time,y=monthly_total_count,color=after_crd))+
    geom_point()+
    geom_smooth(method="lm")

impact %>% 
    group_by(after_crd,time) %>% 
    summarize(monthly_total_count = mean(total_count),
              monthly_agg_claim = mean(agg_claim),
              monthly_avg_claim = mean(avg_claim)) %>%
    ggplot(aes(x=time,y=monthly_agg_claim,color=after_crd))+
    geom_point()+
    geom_smooth(method="lm")

impact %>% 
    group_by(after_crd,time) %>% 
    summarize(monthly_total_count = mean(total_count),
              monthly_agg_claim = mean(agg_claim),
              monthly_avg_claim = mean(avg_claim)) %>%
    ggplot(aes(x=time,y=monthly_avg_claim,color=after_crd))+
    geom_point()+
    geom_smooth(method="lm")
```

```{r, eval=F}
a = impact %>% 
        filter(after_crd==F) %>% 
        group_by(mth_out,time) %>% 
        summarize(monthly_total_count = mean(total_count),
                  monthly_agg_claim = mean(agg_claim),
                  monthly_avg_claim = mean(avg_claim)) 
b = impact %>% 
        filter(after_crd==T) %>% 
        group_by(mth_out,time) %>% 
        summarize(monthly_total_count = mean(total_count),
                  monthly_agg_claim = mean(agg_claim),
                  monthly_avg_claim = mean(avg_claim)) 

c = impact %>% 
        filter(is.na(after_crd)) %>% 
        group_by(mth_out,time) %>% 
        summarize(monthly_total_count = mean(total_count),
                  monthly_agg_claim = mean(agg_claim),
                  monthly_avg_claim = mean(avg_claim)) 

ggplot(mapping = aes(x=time,y=monthly_total_count,color=factor(mth_out)))+
        #geom_point(data=a)+
        geom_smooth(data=a,method="lm",se=F)+
        #geom_point(data=b)+
        geom_smooth(data=b,method="lm",se=F)+
        geom_smooth(data=c,se=T)
```



```{r Separate data in to control and not_control group}
not_control = impact %>% filter(!is.na(mth_out))
control = impact %>% filter(is.na(mth_out))
```

```{r, by crd only, eval = F}
signif_level = 0.05
test_type = "greater"

### Raw comparison
tmp = not_control %>% group_by(crd,after_crd,id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key=after_crd,value=avg_mthly_claim) %>% ungroup()

is_effective=tmp$`TRUE`<tmp$`FALSE`

tmp = tmp %>% cbind(eff=is_effective)
x = tmp %>% group_by(crd) %>%
        summarize(n_eff=sum(eff),
                  n_not_eff=sum(!eff),
                  n=n(),
                  eff_prop=mean(eff))

## Test for Normality
tmp = not_control %>% group_by(crd, after_crd, id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key = after_crd, value = avg_mthly_claim) %>% ungroup()

diff = tmp$`FALSE` - tmp$`TRUE`
shapiro.test(diff) #small p-value, not Normal, note sample size big
ks.test(diff,"pnorm") #small p-value, not Normal, note sample size big
ggqqplot(diff) #looking at qqplot and density, pretty Normal
ggplot()+geom_density(aes(x=diff))

## Test for significance in difference

#paired t test - assume Normal
not_control %>% group_by(crd, 
                         after_crd, id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key = after_crd, value = avg_mthly_claim) %>% 
        ungroup() %>% group_by(crd) %>% 
        do(tidy(t.test(.$`FALSE`, .$`TRUE`, data=., 
               alternative = test_type, paired = TRUE))) %>% 
        mutate(is_eff = p.value<signif_level) %>% 
        select(crd, 
               is_eff) %>% data.frame(x) 
        
#wilcoxon signed-rank test - not Normal
not_control %>% group_by(crd, 
                         after_crd, id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key = after_crd, value = avg_mthly_claim) %>% 
        ungroup() %>% group_by(crd) %>% 
        do(tidy(wilcox.test(.$`FALSE`, .$`TRUE`, data=., 
                       alternative = test_type, paired = TRUE))) %>% 
        mutate(is_eff = p.value<signif_level) %>% 
        select(crd, 
               is_eff) %>% data.frame(x) 
```
```{r, by all attribute besides age, eval = F}
tmp = not_control %>% group_by(age,gender,chronic_count,
                               is_lowincome,rural,region,crd,
                               after_crd,id) %>% 
    summarize(avg_mthly_claim = mean(agg_claim)) %>% 
    spread(key=after_crd,value=avg_mthly_claim) %>% ungroup()

is_effective=tmp$`TRUE`<tmp$`FALSE`
tmp = tmp %>% cbind(eff=is_effective)

x = tmp %>% group_by(age,gender,chronic_count,
                 is_lowincome,rural,region,crd) %>%
    summarize(n_eff=sum(eff),
              n=sum(eff+!eff),
              eff_prop=mean(eff))
```
```{r, by all attribute, eval = F}
signif_level = 0.05
test_type = "greater"

### Raw comparison
tmp = not_control %>% group_by(age,gender,chronic_count,
                 is_lowincome,rural,region,crd,
                 after_crd,id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key=after_crd,value=avg_mthly_claim) %>% ungroup()

is_effective=tmp$`TRUE`<tmp$`FALSE`

tmp = tmp %>% cbind(eff=is_effective)
x = tmp %>% group_by(age,gender,chronic_count,
                 is_lowincome,rural,region,crd) %>%
        summarize(n_eff=sum(eff),
                  n_not_eff=sum(!eff),
                  n=n(),
                  eff_prop=mean(eff))

## Test for Normality
tmp = not_control %>% group_by(age,gender,chronic_count,
                 is_lowincome,rural,region,crd,
                 after_crd, id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key = after_crd, value = avg_mthly_claim) %>% ungroup()

diff = tmp$`FALSE` - tmp$`TRUE`
shapiro.test(diff) #small p-value, not Normal, note sample size big
ks.test(diff,"pnorm") #small p-value, not Normal, note sample size big
ggqqplot(diff) #looking at qqplot and density, pretty Normal
ggplot()+geom_density(aes(x=diff))

## Test for significance in difference

#paired t test - assume Normal
not_control %>% group_by(age,gender,chronic_count,
                 is_lowincome,rural,region,crd,
                 after_crd, id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key = after_crd, value = avg_mthly_claim) %>% 
        ungroup() %>% group_by(age,gender,chronic_count,
                 is_lowincome,rural,region,crd) %>% 
        do(tidy(t.test(.$`FALSE`, .$`TRUE`, data=., 
               alternative = test_type, paired = TRUE))) %>% 
        mutate(is_eff = p.value<signif_level) %>% 
        select(age,gender,chronic_count,
               is_lowincome,rural,region,crd,
               is_eff) %>% data.frame(x) 
        
#wilcoxon signed-rank test - not Normal
x = not_control %>% group_by(age,gender,chronic_count,
                         is_lowincome,rural,region,crd, 
                         after_crd, id) %>% 
        summarize(avg_mthly_claim = mean(agg_claim)) %>% 
        spread(key = after_crd, value = avg_mthly_claim) %>% 
        ungroup() %>% group_by(age,gender,chronic_count,
                 is_lowincome,rural,region,crd) %>% 
        do(tidy(wilcox.test(.$`FALSE`, .$`TRUE`, data=., 
                       alternative = test_type, paired = TRUE))) %>% 
        mutate(is_eff = p.value<signif_level) %>% 
        select(age,gender,chronic_count,
               is_lowincome,rural,region,crd,
               is_eff) %>% data.frame(x) %>% 
    select(age,gender,chronic_count,
           is_lowincome,rural,region,crd,
           n_eff,n_not_eff,n,eff_prop,
           is_eff)
```

```{r, fig.width=9000, fig.height=800}
t=list()
tmp=list()
for(i in 1:4){
        tmp[[i]] = not_control %>% filter(crd == i)
        
        df = tmp[[i]] %>% group_by(after_crd,id) %>% 
                summarize(avg_mthly_claim = mean(agg_claim)) %>% 
                spread(key=after_crd,value=avg_mthly_claim) %>% ungroup()
        
        is_effective=ifelse(df$`TRUE`<df$`FALSE`,"Y","N")
        
        df = df %>% cbind(is_eff=is_effective)
        df = df %>% inner_join(demo,by="id") %>% 
                select(-c("FALSE","TRUE","id","mth_out","crd")) %>% 
                mutate(is_lowincome=as.factor(is_lowincome),
                       region=as.factor(region),
                       rural=as.factor(rural),
                       gender=as.factor(gender)
                )
        
        t[[i]] = C5.0(is_eff~.-is_eff, data=df)
        print(summary(t[[i]]))
}
```

